# Generated by Django 3.1.2 on 2020-10-04 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('key_word', models.CharField(max_length=20, verbose_name='Key Word')),
                ('pages', models.IntegerField(verbose_name='Pages')),
                ('source', models.CharField(choices=[('node', 'Node'), ('python', 'Python')], default='node', max_length=10, verbose_name='Source')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pendind', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Executions',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('highlight', models.CharField(max_length=50, verbose_name='Highlight')),
                ('link', models.CharField(max_length=300, verbose_name='Link')),
                ('original_price', models.CharField(max_length=10, verbose_name='Original Price')),
                ('discount_price', models.CharField(max_length=10, verbose_name='Discount Price')),
                ('discount_percentage', models.CharField(max_length=5, verbose_name='Discount')),
                ('installments', models.CharField(max_length=30, verbose_name='Installments')),
                ('price_per_installment', models.CharField(max_length=10, verbose_name='Price per Installment')),
                ('store_link', models.CharField(max_length=300, verbose_name='Store Link')),
                ('store', models.CharField(max_length=50, verbose_name='Store')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_libre.execution', verbose_name='Execution')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
